### ISSUE TITLE
Continuar con el proyecto

### ISSUE THREAD

**Issue by abusiv0** [GoDKeR/ArgentumOnline-Csharp#1]
Hola que tal? me encantaría continuar este proyecto pero creo que faltan algunos archivos, podrías pasarme la solución completa? quiero continuarlo de forma open source

**Comment by GoDKeR** [comment]
El código de esto ya no existe en ningún otro lado que no sea GitHub, igual esto era mas una prueba de concepto que algo usable, creo que ni siquiera tiene el protocolo hecho.
